# image: $CI_REGISTRY_IMAGE/taste:latest
image: dmt:latest

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID            # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == 'CoRA-EBB' # Execute jobs when a new commit is pushed to any branch

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - post_build

build:
  stage: build
  script:
    - ./configure ; pip3 install --upgrade . ; LANG=C LC_ALL=C PATH=$PATH:/asn1scc make
  # artifacts:
    # paths:
    #   - 'test/logs/*.err.txt'
    # when: on_failure
    # expire_in: 2 weeks
